package model
import (
	"time"
	)


// ViewRequest is the set of parameters for view request
type ViewRequest struct {
	Condition map[string]interface{} `json:"condition"`
	Order     map[string]int         `json:"order"`
	Limit     *int64                 `json:"limit"`
	Offset    *int64                 `json:"offset"`
}




//////////////////http request



//request

type RequestTokenizedCards struct {
	Cardreference string            `json:"cardreference"`
	
}

type RequestPayment struct {
	Clientreference string            `json:"clientreference"`
	Paymentreference  string      `json:"paymentreference"`
	Token  string      `json:"Token"`
	Cvv  string      `json:"Cvv"`
	Amount  string      `json:"Amount"`
}

type RequestTokenized struct {

	Clientreference string            `json:"clientreference"`
	Paymentreference string            `json:"paymentreference"`
	Card  string      `json:"card"`
	Exp  string      `json:"exp"`
	Cvv  string      `json:"Cvv"`
}


type myDataService01 struct {
	Idreference string            `json:"Idreference"`
	Idcomercio  string      `json:"Idcomercio"`
}



type AutoGenerated struct {
	StatusMessage string       `json:"status_message"`
    Status string       `json:"status"`
	Cards       []CardData `json:"card_data"`
}

type CardData struct {
	Date time.Time `json:"card_date"`
	Token  string   `json:"card_token"`
    LastDigits  string   `json:"card_last"`
	Marca  string   `json:"card_brand"`
	Vigencia  string   `json:"card_exp"`
	Bin  string   `json:"card_bin"`
	Score  string   `json:"card_score"`
	Type  string   `json:"type_card"`

}



type AutoGeneratedDash struct {
	StatusMessage string       `json:"status_message"`
    Status string       `json:"status"`
    GroupNumber string  `json:"groupnbr"`
	Datadash       []ResponseDatadash `json:"dash_data"`
}

type ResponseDatadash struct {
	Date time.Time `json:"data_date"`
	Secuence  string   `json:"data_sec"`
    NameColumn  string   `json:"data_name"`
	CreatedAt  string   `json:"data_time"`
	Valuecolumna  string   `json:"data_valuec"`
	Valoramount  string   `json:"data_valuea"`

}


type RequestDash01Grafica01 struct {
	Dash0101reference string            `json:"reference"`
	Dash0101reference2  string      `json:"reference2"`
	Dash0101Dato01  string      `json:"dato01"`
	Dash0101Dato02  string      `json:"dato02"`
	Dash0101Dato03  string      `json:"dato03"`
}



type RequestDash01Grafica02 struct {
	Dash0102reference string            `json:"reference"`
	Dash0102reference2  string      `json:"reference2"`
	Dash0102Dato01  string      `json:"dato01"`
	Dash0102Dato02  string      `json:"dato02"`
	Dash0102Dato03  string      `json:"dato03"`
}


type RequestDash02Grafica01 struct {
	Dash0201reference string            `json:"reference"`
	Dash0201reference2  string      `json:"reference2"`
	Dash0201Dato01  string      `json:"dato01"`
	Dash0201Dato02  string      `json:"dato02"`
	Dash0201Dato03  string      `json:"dato03"`
}
type RequestDash02Grafica02 struct {
	Dash0202reference string            `json:"reference"`
	Dash0202reference2  string      `json:"reference2"`
	Dash0202Dato01  string      `json:"dato01"`
	Dash0202Dato02  string      `json:"dato02"`
	Dash0202Dato03  string      `json:"dato03"`
}

type RequestDash02Grafica03 struct {
	Dash0203reference string            `json:"reference"`
	Dash0203reference2  string      `json:"reference2"`
	Dash0203Dato01  string      `json:"dato01"`
	Dash0203Dato02  string      `json:"dato02"`
	Dash0203Dato03  string      `json:"dato03"`
}



type RequestDash03Grafica01 struct {
	Dash0301reference string            `json:"reference"`
	Dash0301reference2  string      `json:"reference2"`
	Dash0301Dato01  string      `json:"dato01"`
	Dash0301Dato02  string      `json:"dato02"`
	Dash0301Dato03  string      `json:"dato03"`
}
type RequestDash03Grafica02 struct {
	Dash0302reference string            `json:"reference"`
	Dash0302reference2  string      `json:"reference2"`
	Dash0302Dato01  string      `json:"dato01"`
	Dash0302Dato02  string      `json:"dato02"`
	Dash0302Dato03  string      `json:"dato03"`
}

type RequestDash03Grafica03 struct {
	Dash0303reference string            `json:"reference"`
	Dash0303reference2  string      `json:"reference2"`
	Dash0303Dato01  string      `json:"dato01"`
	Dash0303Dato02  string      `json:"dato02"`
	Dash0303Dato03  string      `json:"dato03"`
}


/////////////////////response for tokenize

type ResponseTokenize struct {
	StatusMessage string       `json:"status_message"`
	Status       string       `json:"status"`
    Card      CardData `json:"card_data"`
}

type ResponseError struct {
	StatusMessage string       `json:"status_message"`
    Status string       `json:"status"`
}
